version: '3.8'

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hoshimi/data/stock_data

services:
  querier:
    build: ./querier
    volumes:
      - db_data:/data
    environment:
      - DB_PATH=/data/stocks.db
      - TWELVEDATA_API_KEY=${TWELVEDATA_API_KEY}
    restart: "no"

  querier_python:
    build: ./yfinance_querier
    volumes:
      - db_data:/data
    environment:
      - DB_PATH=/data/stocks.db
      - SYMBOL=AAPL
      - INTERVAL=1m
      - PERIOD=1d
    restart: "no"

  analyzer_python:
    build: ./analyzer/py
    volumes:
      - db_data:/data
    environment:
      - DB_PATH=/data/stocks.db
    restart: unless-stopped

  analyzer_cpp:
    build: ./analyzer/cpp
    volumes:
      - db_data:/data
    environment:
      - DB_PATH=/data/stocks.db
    restart: unless-stopped

  ui-api-gateway:
    build: ./ui-api-gateway
    ports:
      - "6330:8080"
    volumes:
      - db_data:/data
    environment:
      - DB_PATH=/data/stocks.db
      - PORT=8080
      - DATA_SERVER_BASE=http://localhost:3881
